### ISSUE TITLE
sorting functionality

### ISSUE THREAD

**Issue by midas643** [dzzie/IDACompare#2]
I would appreciate sorting in dialog for snapshot saving because I usually want to save only particular function into mdb file and scrolling down and up to find it is kinda annoying and takes too much time.

**Comment by dzzie** [comment]
in the lower matches made list I can easily add an option to delete selected entries from database. currently remove option only hides them for current session. Would that help?

in the upper 2 unmatched lists I could potentially add this as well, but have to check if setting them to multiselect will impact anything else.

**Comment by dzzie** [comment]
ok try the current build from teh repo, in addition to above change, i also made the top two lists multiselect, and added a right click option to delete selected. (delete key also works). Once removed from db, they wont show next time you open database. Should fit the bill, and was a very good idea thanks.

**Comment by midas643** [comment]
That's good. What about these columns?
![screen](https://cloud.githubusercontent.com/assets/8516655/7498495/7b021bde-f421-11e4-80f6-4ebf3d361299.png)

**Comment by dzzie** [comment]
the only purpose of the plugin form is to export entire idb to the database, so you wish there was a way to only export a specific function to start with? how would you know which one you wanted though?

**Comment by midas643** [comment]
Export entire .idb for the one you compare to and export just chosen ones from the second idb you compare with to find matches.

**Comment by dzzie** [comment]
ok that is an interesting use scenario that would seriously speed the searches. I can see the use for it. I will add this another good idea!

**Comment by dzzie** [comment]
ok just updated the activex dll plugin ui ( IdaCompare.dll ), overwrite your old one with it. You will have to register it again with regsvr32 [path] from a 32bit instance of cmd.exe (because no compatability is set) or just compile it on your system from vb6.

Rather than column sorting, I added a textbox to allow you to filter the list based on function name.
(sorting I would have to change format of all the data added to it and test allot) 

So if you name target functions with a prefix, you could find them in 1 second flat. Also this way I could save last filter used per database if necessary, but I think its so easy now that shouldnt be necessary. If the filter is active, then it will only export the displayed functions.

**Comment by dzzie** [comment]
i just updated the installer in the repo too, thats probably an easier way to get it registered

**Comment by midas643** [comment]
That's brilliant now, much easier to work with... I really appreciate your work on the project. :octocat:  :) Filter textbox works as it is supposed to be. Just brilliant :+1:

**Comment by dzzie** [comment]
ok great :)  thanks again for the suggestions both very good features!
